
# Tomcat Server
server:
  port: 8080

# Logger  
logging.level:
  web: DEBUG

spring:
# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: rootroot